ALTER TABLE enumeration_shards
  ADD COLUMN IF NOT EXISTS pages_processed BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS observed_id_positions BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS observed_users BIGINT NOT NULL DEFAULT 0;
